document.createElement('nav');
document.createElement('article');
document.createElement('section');
document.createElement('aside');
document.createElement('header');
document.createElement('footer');
document.createElement('figcaption');
document.createElement('figure');
document.createElement('main');